/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScopedParent {
        /**
          * @default []
         */
        "anArray": any[];
    }
    interface ShadowChild1 {
        /**
          * @default []
         */
        "anArray": any[];
    }
    interface ShadowChild2 {
        /**
          * @default []
         */
        "anArray": any[];
    }
}
declare global {
    interface HTMLScopedParentElement extends Components.ScopedParent, HTMLStencilElement {
    }
    var HTMLScopedParentElement: {
        prototype: HTMLScopedParentElement;
        new (): HTMLScopedParentElement;
    };
    interface HTMLShadowChild1Element extends Components.ShadowChild1, HTMLStencilElement {
    }
    var HTMLShadowChild1Element: {
        prototype: HTMLShadowChild1Element;
        new (): HTMLShadowChild1Element;
    };
    interface HTMLShadowChild2Element extends Components.ShadowChild2, HTMLStencilElement {
    }
    var HTMLShadowChild2Element: {
        prototype: HTMLShadowChild2Element;
        new (): HTMLShadowChild2Element;
    };
    interface HTMLElementTagNameMap {
        "scoped-parent": HTMLScopedParentElement;
        "shadow-child-1": HTMLShadowChild1Element;
        "shadow-child-2": HTMLShadowChild2Element;
    }
}
declare namespace LocalJSX {
    interface ScopedParent {
        /**
          * @default []
         */
        "anArray"?: any[];
    }
    interface ShadowChild1 {
        /**
          * @default []
         */
        "anArray"?: any[];
    }
    interface ShadowChild2 {
        /**
          * @default []
         */
        "anArray"?: any[];
    }
    interface IntrinsicElements {
        "scoped-parent": ScopedParent;
        "shadow-child-1": ShadowChild1;
        "shadow-child-2": ShadowChild2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scoped-parent": LocalJSX.ScopedParent & JSXBase.HTMLAttributes<HTMLScopedParentElement>;
            "shadow-child-1": LocalJSX.ShadowChild1 & JSXBase.HTMLAttributes<HTMLShadowChild1Element>;
            "shadow-child-2": LocalJSX.ShadowChild2 & JSXBase.HTMLAttributes<HTMLShadowChild2Element>;
        }
    }
}
