/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmpChild {
    }
    interface CmpParent {
    }
}
declare global {
    interface HTMLCmpChildElement extends Components.CmpChild, HTMLStencilElement {
    }
    var HTMLCmpChildElement: {
        prototype: HTMLCmpChildElement;
        new (): HTMLCmpChildElement;
    };
    interface HTMLCmpParentElement extends Components.CmpParent, HTMLStencilElement {
    }
    var HTMLCmpParentElement: {
        prototype: HTMLCmpParentElement;
        new (): HTMLCmpParentElement;
    };
    interface HTMLElementTagNameMap {
        "cmp-child": HTMLCmpChildElement;
        "cmp-parent": HTMLCmpParentElement;
    }
}
declare namespace LocalJSX {
    interface CmpChild {
    }
    interface CmpParent {
    }
    interface IntrinsicElements {
        "cmp-child": CmpChild;
        "cmp-parent": CmpParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cmp-child": LocalJSX.CmpChild & JSXBase.HTMLAttributes<HTMLCmpChildElement>;
            "cmp-parent": LocalJSX.CmpParent & JSXBase.HTMLAttributes<HTMLCmpParentElement>;
        }
    }
}
