/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleScoped {
    }
    interface ExampleShadow {
    }
}
declare global {
    interface HTMLExampleScopedElement extends Components.ExampleScoped, HTMLStencilElement {
    }
    var HTMLExampleScopedElement: {
        prototype: HTMLExampleScopedElement;
        new (): HTMLExampleScopedElement;
    };
    interface HTMLExampleShadowElement extends Components.ExampleShadow, HTMLStencilElement {
    }
    var HTMLExampleShadowElement: {
        prototype: HTMLExampleShadowElement;
        new (): HTMLExampleShadowElement;
    };
    interface HTMLElementTagNameMap {
        "example-scoped": HTMLExampleScopedElement;
        "example-shadow": HTMLExampleShadowElement;
    }
}
declare namespace LocalJSX {
    interface ExampleScoped {
    }
    interface ExampleShadow {
    }
    interface IntrinsicElements {
        "example-scoped": ExampleScoped;
        "example-shadow": ExampleShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-scoped": LocalJSX.ExampleScoped & JSXBase.HTMLAttributes<HTMLExampleScopedElement>;
            "example-shadow": LocalJSX.ExampleShadow & JSXBase.HTMLAttributes<HTMLExampleShadowElement>;
        }
    }
}
